### ISSUE TITLE
Global counter mismatch 

### ISSUE THREAD

**Issue by Doomsel** [coldphysics/experiment-control#2] opened 2020-03-06 12:04 UTC
**Describe the bug**
Sometimes after fast switching of models or quickly repeated starts and stops of the iteration (with the ''increment iterator'' button), the global counter of the data (of the trace and database entry) is one larger than the  one given as ''start global counter''. It seems that it depends on the progress of the running cycle if this problem occures

**To Reproduce**
1. Click ''Start''
2. Check ''increment iterator'' several times during one cycle
3. Iterator missmatch

**Expected behavior**
The global counter of the data and the shown "start global counter" match

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Control Version: 1.3.0.25
 - Hardware Type: NI

**Comment by ghareeb-falazi** [comment] 2020-04-20 14:02
> he global counter of the data (of the trace and database entry) is one larger than the one given as ''start global counter''

What do you mean with the "start global counter"? is it one of the counters shown on the UI, or is it one of the database columns? Also, could you attach a screenshot of an example case?

**Comment by Doomsel** [comment] 2020-04-20 15:46
I will be at the office again tomorrow, then i will provide more info and a screenshot. With the "start global counter" i mean the value shown on the main panel of the experiment control program which is also written to the database. But i have to look it up how it is called there.

**Comment by Doomsel** [comment] 2020-04-22 15:15
![grafik](https://user-images.githubusercontent.com/3749879/79999635-6e737580-84bc-11ea-8717-730eb67f8461.png)

The blue circled value in the picture above and the `StartCounterOfScans` value in the database are not maching with the "real" starting global counter. For example if the value reads 2418758 the first measurement of the iteration would be 241875**9** if this error occures.

**Comment by ghareeb-falazi** [comment] 2020-04-29 21:31
I did some changes in PR #10 , but since I couldn't reliably reproduce the exact bug mentioned here, I am not sure if the PR solves the issue or not
when the new release comes out, we need to check if the bug persists and reopen this issue. For now I will close it.

**Closed as completed by ghareeb-falazi** 2020-04-29 21:31 UTC
Labels: bug
