### ISSUE TITLE
Iterator variable not iterated correctly: Keeps the Start value and claims Number of Iterations = 1

### ISSUE THREAD

**Issue by Denstorefisk** [coldphysics/experiment-control#42] opened 2021-01-18 10:12 UTC
**Describe the bug**
When a non-iterator variable is turned into an iterator and the iteration is started without some update of the variable, the number of iterations is not correctly calculated, instead the software makes only a single iteration and in each scan. 

**To Reproduce**
1. Install 1.4.4
2. Open a model and go to variable window
3. right click a static variable and make it an iterator
4. Start iterating right away **without making changes of cur, start, stop, step fields**
5. The iterator now changes current to the start-value, but does not iterate from this value. Instead the main window shows that the Number of Iterations = 1.
6. The main window now just increase the global counter as if there is only one point in the iterator.

**Expected behavior**
When pressing increment iterators, the program is expected to change the current value to the start value and iterate the current value in steps given by Step until `(Stop <= Curr.+Step) == True`.

**Screenshots**

![number_of_iterations_wrong_0](https://user-images.githubusercontent.com/63640986/104903053-d7bae300-597f-11eb-96da-8a0d3e3928ae.PNG)

![number_of_iterations_wrong_1](https://user-images.githubusercontent.com/63640986/104903056-d7bae300-597f-11eb-97d7-e4e7a33fd802.PNG)

![number_of_iterations_wrong_2](https://user-images.githubusercontent.com/63640986/104903057-d8537980-597f-11eb-8b7d-e319c2fe2404.PNG)

![number_of_iterations_wrong_3](https://user-images.githubusercontent.com/63640986/104903058-d8537980-597f-11eb-90d2-58ceb6112715.PNG)

![number_of_iterations_wrong_4](https://user-images.githubusercontent.com/63640986/104903059-d8ec1000-597f-11eb-84e6-c0c6d37cf260.PNG)

![number_of_iterations_wrong_5](https://user-images.githubusercontent.com/63640986/104903049-d689b600-597f-11eb-8ed8-263649cc63ad.PNG)

**In this case, the software behaves as expected:**

![number_of_iterations_wrong_6](https://user-images.githubusercontent.com/63640986/104903050-d7224c80-597f-11eb-9617-ad84e1cf64b8.PNG)

![number_of_iterations_wrong_7](https://user-images.githubusercontent.com/63640986/104903052-d7224c80-597f-11eb-8909-049ad93de99b.PNG)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Software Control Version 1.4.4
 - AdWin ststem

**Comment by ghareeb-falazi** [comment] 2021-01-31 16:02
@Denstorefisk  I think I identified where the problem is and I'm working on it

**Comment by ghareeb-falazi** [comment] 2021-02-01 10:07
@Denstorefisk  Fix will be included in the next release

**Closed as completed** 2021-02-01 10:06 UTC
Labels: bug
